version: '3'

services:

  temperature:
    image: pluspeterpublic/temperature:latest
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
    restart: unless-stopped

  windspeed:
    image: pluspeterpublic/windspeed:latest
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: unless-stopped

  app:
    image: php:7.1
    command: php /app/bin/console server:run 0.0.0.0:8081
    ports:
      - "8081:8081"
    volumes:
      - ./app:/app
    depends_on:
      - composer

  composer:
    image: composer
    command: install
    volumes:
      - ./app:/app
